version: ~> 1.0
language: cpp
dist: bionic
osx_image: xcode11.3

cache:
  - ccache
  - directories:
      - $TRAVIS_BUILD_DIR/deps

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-9
      - cmake-data
      - cmake
      - libopenblas-dev
  homebrew:
    taps:
      - cstatz/homebrew-visit
    packages:
      - ccache
      - cmake
      - blaze
    update: true

os:
  - linux
  - osx

compiler:
  - g++-9
  - clang

jobs:
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export BLAZE_INSTALL_DIR=`pwd`/deps/blaze;
    wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.7.tar.gz;
    export BLAZE_INSTALL_DIR=`pwd`/deps/blaze;
    echo ${BLAZE_INSTALL_DIR};
    tar -xf blaze-3.7.tar.gz;
    cd blaze-3.7;
    mkdir build;
    cd build;
    cmake ../ -DCMAKE_INSTALL_PREFIX=$BLAZE_INSTALL_DIR;
    cmake --build .;
    cmake --build . -- install;
    cd ..;
    cd ..;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CXX=${TRAVIS_COMPILER};
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "g++-9" ]]; then
      export CC=gcc-9;
      export CXX=g++-9;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "clang" ]]; then
    export CC=clang;
    export CXX=clang++;
    fi
  - pwd
  - mkdir -p cmake_build_release
  - pushd cmake_build_release
  - export BLAZE_INCLUDE=""
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export BLAZE_INCLUDE="`pwd`/deps/blaze/include";
  - fi
  - cmake -DCMAKE_BUILD_TYPE=Release ../ -DBUILD_TEST:BOOL=true -DENABLE_TEST:BOOL=true -DBLAZE_INCLUDE:STRING="$BLAZE_INCLUDE"
  - cmake --build .
  - ctest -V
  - popd
  - rm -rf cmake_build_release

