name: blazertCI
on: [push, pull_request]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: prepare dependencies
      - run: echo `pwd`
      - run: export BLAZE_INSTALL_DIR=`pwd`/deps/blaze;
      - run: wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.7.tar.gz;
      - run: export BLAZE_INSTALL_DIR=`pwd`/deps/blaze;
      - run: echo ${BLAZE_INSTALL_DIR};
      - run: tar -xf blaze-3.7.tar.gz;
      - run: cd blaze-3.7;
      - run: mkdir build;
      - run: cd build;
      - run: cmake ../ -DCMAKE_INSTALL_PREFIX=$BLAZE_INSTALL_DIR;
      - run: cmake --build .;
      - run: cmake --build . -- install;
      - run: cd ..;
      - run: cd ..;

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build blazert
      - uses: actions/checkout@v2
      - run: export BLAZE_INCLUDE=""
      - run: export BLAZE_INCLUDE=`pwd`/deps/blaze/include;
      - run: export CXX=${TRAVIS_COMPILER};
      - run: export CC=gcc-9;
      - run: export CXX=g++-9;
      - run: pwd
      - run: mkdir -p cmake_build_release
      - run: pushd cmake_build_release
      - run: cmake -DCMAKE_BUILD_TYPE=Release ../ -DBUILD_TEST:BOOL=true -DBUILD_EXAMPLES:BOOL=true -DBLAZE_INCLUDE_OVERRIDE:STRING=${BLAZE_INCLUDE} -DENABLE_OMP:BOOL=false
      - run: cmake --build .

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
      - run: ctest --progress -VV